global:
  scrape_interval: 10s  # Set the scrape interval to every 15 seconds.
  evaluation_interval: 10s  # Evaluate rules every 15 seconds.

scrape_configs:
  - job_name: 'nsp-kafka'
    scrape_interval: 30s  # Override the global scrape interval for this job.
    static_configs:
      - targets: ['kafka-alert-exporter:8001']
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'alertmanager:9093'  # Make sure this matches your Alertmanager container hostname

rule_files:
  - "alert_rules.yml"  # Create this file to define alerting rules